#! /bin/sh
#


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
LCD=/home/pi/repos/piplate_lcdproc_server/python/server.py
DAEMON=/home/pi/repos/piplate_lcdproc_server/cli_server.php
NAME="phpLCDd"
DESC="phpLCDd"

nohup python $LCD > /dev/null 2>&1 & 
sleep 1
nohup php -f $DAEMON > /dev/null 2>&1 &

exit 0
